name: SwiftLint

on: push

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Strict linting
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
